version: "3"

services:
  nginx:
    image: lemello091085/nginx_test:latest
    ports:
      - 80:80
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mellole
    ports: 
      - 3308:3306
